# Download as an .rmd file to use in R

---
title: "Jessica C - summer analysis 2025"
author: "Madison Chisholm"
date: "2025-05-20"
output: pdf_document
---
```{r}
#load needed libraries (must import if not downloaded already into r)
install.package('readxl')
library(readxl)
```

```{r}
# Load the file using pathname (make sure file in the R directory to import)
df <- read_excel("/Users/jessi/OneDrive/Desktop/MRI R/jessica_d_group_image.xlsx")

#convert group and image to factor instead of numeric 
df$group <- as.factor(df$group)
df$image <- as.factor(df$image)
head(df)
```

```{r}
#run one-way anova 
anova_model <- aov(d ~ group, data = df)
```

```{r}
#Shapiro-Wilk test for normality; if p-value > 0.05 then good (I think)
shapiro.test(residuals(anova_model))
```
```{r}
#Levene's test for homogeneity of variances; if p-value > 0.05 then good (I think)
library(car)
leveneTest(d ~ group, data = df)
```
```{r}
#re-run ANOVA with summary output; if p-value < 0.05 then good (I think)
anova_model <- aov(d ~ group, data = df)
summary(anova_model)
```
```{r}
#Post-hoc Tukey HSD test to see groupwise comparisons; if p-value < 0.05 then good (I think)
TukeyHSD(anova_model)
```




